apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "audit.name" . }}
  labels:
    app: {{ template "hygieia.name" . }}
    chart: {{ template "hygieia.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.audit.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "hygieia.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "hygieia.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: waiting-for-mongodb
        image: busybox
        command: 
          - 'sh'
          - '-c'
          - 'until nslookup {{ .Release.Name }}-mongodb; do echo waiting for mongodb; sleep 2; done;'
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.audit.image.repository }}:{{ .Values.audit.image.tag }}"
          imagePullPolicy: {{ .Values.audit.image.pullPolicy }}
          env:
{{- include "generate_env" . | indent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
# TODO: Find or implement a healthcheck api
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
{{ toYaml .Values.audit.resources | indent 12 }}
    {{- with .Values.audit.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.audit.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.audit.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
