apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "hygieia.fullname" . }}-ui
  labels:
    app: {{ template "hygieia.name" . }}
    chart: {{ template "hygieia.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "hygieia.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "hygieia.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: waiting-for-api
        image: busybox
        command: 
          - 'sh'
          - '-c'
          - 'until nslookup {{ .Release.Name }}-api; do echo waiting for hygieia-api; sleep 2; done;'
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
{{-  range $key, $val := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ toString $val | quote }}
{{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
# TODO: Find or implement a healthcheck api
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
{{ toYaml .Values.ui.resources | indent 12 }}
    {{- with .Values.ui.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ui.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ui.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
