apiVersion: v1
kind: Service
metadata:
  name: {{ template "hygieia.fullname" . }}-ui
  labels:
    app: {{ template "hygieia.name" . }}
    chart: {{ template "hygieia.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "hygieia.name" . }}
    release: {{ .Release.Name }}
