# Default values for api.
# This is a YAML formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nexusread.aa.com:18444/hygieia-api
  tag: 2.0.5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

env:
  SPRING_DATA_MONGODB_HOST: mongodb
  SPRING_DATA_MONGODB_PORT: 27017
  SPRING_DATA_MONGODB_DATABASE: dashboarddb
  SPRING_DATA_MONGODB_USERNAME: dashboarduser
  SPRING_DATA_MONGODB_PASSWORD: dbpassword
  #API encryption key. Optional. See http://capitalone.github.io/Hygieia/setup.html#encryption for private-repos	
  KEY: ""
  LOG_REQUEST: false
  LOG_SPLUNK_REQUEST: false
  CORS_ENABLED: false
  #CORS_WHITELIST: http://domain1.com:port,http://domain2.com:port
  FEATURE_DYNAMIC_PIPELINE: disabled
  #Authentication Settings
  # JWT expiration time in milliseconds
  AUTH_EXPIRATION_TIME: "60000000"
  # Secret Key used to validate the JWT tokens
  #AUTH_SECRET: hygieiasecret
  AUTH_AUTHENTICATION_PROVIDERS: STANDARD
  # LDAP Server Url, including port of your LDAP server
  #AUTH_LDAP_SERVER_URL: 
  # If using standard ldap
  # LDAP User Dn Pattern, where the username is replaced with '{0}'
  #AUTH_LDAP_USER_DN_PATTERN: 
  # If using ActiveDirectory
  # This will be the domain part of your userPrincipalName
  #AUTH_AD_DOMAIN: 
  # This will be your root dn
  #AUTH_AD_ROOT_DN: 
  # This is your active directory url
  #AUTH_AD_URL: 
  # Needed if you want to query ldap
  #AUTH_LDAP_BIND_USER: 
  #AUTH_LDAP_BIND_PASS: 
  #Monitor Widget proxy credentials
  #MONITOR_PROXY_USERNAME: 
  #MONITOR_PROXY_PASSWORD: 
  #Monitor Widget proxy information
  #MONITOR_PROXY_TYPE: http
  #MONITOR_PROXY_HOST: 
  #MONITOR_PROXY_PORT: 80
