# Default values for hygieia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env:
  SPRING_DATA_MONGODB_HOST: mongodb
  SPRING_DATA_MONGODB_PORT: 27017
  SPRING_DATA_MONGODB_DATABASE: dashboarddb
  SPRING_DATA_MONGODB_USERNAME: dashboarduser
  SPRING_DATA_MONGODB_PASSWORD: dbpassword
  #API encryption key. Optional. See http://capitalone.github.io/Hygieia/setup.html#encryption for private-repos	
  KEY: ""
  LOG_REQUEST: false
  LOG_SPLUNK_REQUEST: false
  CORS_ENABLED: false
  #CORS_WHITELIST: http://domain1.com:port,http://domain2.com:port
  FEATURE_DYNAMIC_PIPELINE: disabled
  #Authentication Settings
  # JWT expiration time in milliseconds
  AUTH_EXPIRATION_TIME: "60000000"
  # Secret Key used to validate the JWT tokens
  #AUTH_SECRET: hygieiasecret
  AUTH_AUTHENTICATION_PROVIDERS: STANDARD
  # LDAP Server Url, including port of your LDAP server
  #AUTH_LDAP_SERVER_URL: 
  # If using standard ldap
  # LDAP User Dn Pattern, where the username is replaced with '{0}'
  #AUTH_LDAP_USER_DN_PATTERN: 
  # If using ActiveDirectory
  # This will be the domain part of your userPrincipalName
  #AUTH_AD_DOMAIN: 
  # This will be your root dn
  #AUTH_AD_ROOT_DN: 
  # This is your active directory url
  #AUTH_AD_URL: 
  # Needed if you want to query ldap
  #AUTH_LDAP_BIND_USER: 
  #AUTH_LDAP_BIND_PASS: 
  #Monitor Widget proxy credentials
  #MONITOR_PROXY_USERNAME: 
  #MONITOR_PROXY_PASSWORD: 
  API_HOST: api
  API_PORT: "8080"

# Mongodb default configurations
mongodb:
  persistence:
    enabled: false
  usePassword: true # Enable authentication
  # MongoDB admin password
  # ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
  mongodbRootPassword: admin
  # MongoDB custom user and database
  # ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#creating-a-user-and-database-on-first-run
  mongodbUsername: username
  mongodbPassword: password
  mongodbDatabase: databas

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - dashboard.com
  tls: []

api:
  replicaCount: 1
  image:
    repository: hygieia/api
    tag: 2.0.5
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources: {}

audit:
  image:
    repository: hygieia/api-audit
    tag: 2.0.5
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  resources: {}

ui:
  replicaCount: 1
  image:
    repository: hygieia/ui
    tag: 2.0.5
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
